Update the block header and previous certificate in grpc blockinfo
zarbchain/zarb-go pull request #250
Opened 2022-02-20 15:54 UTC by nagarajmanjunath

## Description

* Fix gRPC proto.
* Updated the block info response with block header and previous hash certificate.
* Fix the test cases.

## Checklist

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] CHANGELOG is updated.

2022-02-20 16:49 UTC, b00f requested changes

2022-02-20 16:49 UTC, b00f commented on www/grpc/proto/zarb.pb.go
> +// 	protoc-gen-go v1.25.0
I think your protoc version is old.

2022-02-20 17:02 UTC, nagarajmanjunath commented on www/grpc/proto/zarb.pb.go
> +// 	protoc-gen-go v1.25.0
I ll update it.

2022-02-21 05:32 UTC, b00f approved these changes

2022-02-21 06:07 UTC, merged