Disable heartbeat if duration set to zero
zarbchain/zarb-go pull request #364
Opened 2022-09-01 03:03 UTC by jwmdev

## Description

Disable sync hearbeat if heartbeat dealy is set to zero. This also prevents hearbeat ticker from panic if the duration is zero.

## Related issue(s)

Disable heartbeat #164 

## Checklist

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] CHANGELOG is updated.

2022-09-01 03:34 UTC, b00f requested changes

2022-09-01 03:34 UTC, b00f commented on sync/config.go
> +// IMPORTANT NOTE:
This comment here is not useful. Code is very clear. 
We should inform end user. Please remove this comment and update example: https://github.com/zarbchain/zarb-go/blob/main/node/config/example_config.toml

Example config will be created if user create a new node.

2022-09-01 03:34 UTC, b00f commented on sync/config.go
> +		HeartBeatTimeout: time.Second * 5, //set this value to zero if you want to disable heart beat
This comment here also not necessary. Code is clear.

2022-09-01 03:36 UTC, b00f commented
@jwmdev I noticed that your branch is from old p2p branch. Look at the commits here. It's recommended to create new branch from the latest main branch.

2022-09-01 07:47 UTC, jwmdev commented
improved the comments... I will update the repo after merging this PR

2022-09-01 09:25 UTC, b00f commented on sync/sync.go
> +	if sync.config.HeartBeatTimeout > 0 { //this is to prevent calling Stop on a null heartBeatTicker
I suggest change this condition to: `if sync.heartBeatTicker != nil`

2022-09-01 09:26 UTC, b00f requested changes
@jwmdev Better to check if heartBeatTicker is not nil to stop it.

2022-09-02 03:20 UTC, b00f commented
@jwmdev LGTM. Thank you so much.

2022-09-02 03:20 UTC, b00f approved these changes

2022-09-02 03:21 UTC, merged